config/routes.rb
Rails.application.routes.draw do
  root "landing#index"

  get "signup", to: "users#new", as: "user_signup"
  post "signup", to: "users#create"
  get "cancel-ticket/:id", to: "tickets#cancel", as: "cancel_ticket"

  get "login", to: "sessions#new", as: "user_login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: "user_logout"

  resources :users, only: [ :show, :edit, :update, :destroy ]


  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }


  authenticated :admin do
    root to: "admin/dashboard#index", as: :authenticated_admin_root
  end


  resources :tickets do
    member do
      patch :cancel
    end
  end


  resources :shows
  resources :movies
  resources :screens
  resources :admins, only: [:index, :show, :edit, :update]
  resources :home, only: [:index]

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :sessions, only: [:new, :create, :destroy]

    # Admin can manage movies & their shows
    resources :movies do
      resources :shows, only: [:index, :new, :create, :edit, :update, :destroy]
    end

    # Admin can manage users and view their tickets
    resources :users do
      member do
        get :tickets
      end
    end
    resources :admins
    resources :tickets
    resources :shows do
      resources :tickets, only: [:create]
    end

    # Admin can manage tickets
    resources :tickets, only: [:index, :destroy]

    # Admin profile management (Admin can update their info)
    resources :admins, only: [:index, :show, :edit, :update]
  end

  # User Routes (Users can only view & book tickets)
  resources :users, only: [:show, :edit, :update] do
    member do
      get :tickets  # View user's booked tickets
    end
  end

  # Movies & Shows (Public users can view)
  resources :movies do
    resources :shows
  end
  resources :shows

  # Shows & Ticket Booking (Users can book tickets)
  resources :shows, only: [:index, :show] do
    resources :tickets, only: [:create]
  end
  resources :movies do
    resources :shows, only: [:index]
  end  
  resources :users do
    member do
      get :tickets
    end
  end
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Tickets (User can view their tickets)
  resources :tickets, only: [:index, :show]


  # Home Page Route
  get "home", to: "home#index", as: "home"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true, uniqueness: false
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :credit_card, presence: true

  # Associations
  has_many :bookings
  has_many :tickets, dependent: :destroy

    # Prevents storing real credit card numbers
    # def masked_credit_card
    #   "**** **** **** " + credit_card[-4..-1]
    # end

end

app/controllers/admin/users_controllers.rb
# class UsersController < ApplicationController
#   before_action :authenticate_admin!, only: [:admin_dashboard, :manage_users, :manage_movies, :manage_shows, :manage_tickets, :create_user, :create_movie, :create_show, :create_ticket]
#   before_action :set_user, only: [:edit, :update, :show, :destroy]
#   before_action :set_movie, only: [:manage_movies, :create_show, :edit_show]
#   before_action :set_show, only: [:manage_shows, :create_ticket]
#
#   # Admin Dashboard: Admin can view all movies, users, shows, and tickets
#   def admin_dashboard
#     @users = User.all
#     @movies = Movie.all
#     @shows = Show.all
#     @tickets = Ticket.all
#   end
#
#   # Admin: View all users
#   def manage_users
#     @users = User.all
#   end
#
#   # Admin: View all movies
#   def manage_movies
#     @movies = Movie.all
#   end
#
#   # Admin: View all shows for a specific movie
#   def manage_shows
#     @movie = Movie.find(params[:movie_id])
#     @shows = @movie.shows
#   end
#
#   # Admin: Create a new user
#   def create_user
#     @user = User.new(user_params)
#     if @user.save
#       redirect_to manage_users_path, notice: 'User created successfully.'
#     else
#       render :manage_users, alert: 'Failed to create user.'
#     end
#   end
#
#   # Admin: Create a new movie
#   def create_movie
#     @movie = Movie.new(movie_params)
#     if @movie.save
#       redirect_to manage_movies_path, notice: 'Movie created successfully.'
#     else
#       render :manage_movies, alert: 'Failed to create movie.'
#     end
#   end
#
#   # Admin: Create a new show for a movie
#   def create_show
#     @show = @movie.shows.new(show_params)
#     if @show.save
#       redirect_to manage_shows_path(movie_id: @movie.id), notice: 'Show created successfully.'
#     else
#       render :manage_movies, alert: 'Failed to create show.'
#     end
#   end
#
#   # Admin: Edit own profile (ID, username, password cannot be updated)
#   def edit
#     @user = current_user
#   end
#
#   # Admin: Update profile (Cannot update ID, username, or password)
#   def update
#     @user = current_user
#     if @user.update_without_password(user_params)
#       redirect_to admin_dashboard_path, notice: 'Profile updated successfully.'
#     else
#       render :edit, alert: 'Failed to update profile.'
#     end
#   end
#
#   # Admin: Edit or Delete Movie
#   def edit_movie
#     @movie = Movie.find(params[:id])
#   end
#
#   def update_movie
#     @movie = Movie.find(params[:id])
#     if @movie.update(movie_params)
#       redirect_to manage_movies_path, notice: 'Movie updated successfully.'
#     else
#       render :edit_movie, alert: 'Failed to update movie.'
#     end
#   end
#
#   def destroy_movie
#     @movie = Movie.find(params[:id])
#     if @movie.destroy
#       redirect_to manage_movies_path, notice: 'Movie deleted successfully.'
#     else
#       redirect_to manage_movies_path, alert: 'Failed to delete movie.'
#     end
#   end
#
#   # Admin: Edit or Delete Show
#   def edit_show
#     @show = Show.find(params[:id])
#   end
#
#   def update_show
#     @show = Show.find(params[:id])
#     if @show.update(show_params)
#       redirect_to manage_shows_path(movie_id: @show.movie.id), notice: 'Show updated successfully.'
#     else
#       render :edit_show, alert: 'Failed to update show.'
#     end
#   end
#
#   def destroy_show
#     @show = Show.find(params[:id])
#     if @show.destroy
#       redirect_to manage_shows_path(movie_id: @show.movie.id), notice: 'Show deleted successfully.'
#     else
#       redirect_to manage_shows_path(movie_id: @show.movie.id), alert: 'Failed to delete show.'
#     end
#   end
#
#   # Admin: Create/View/Edit/Delete Tickets
#   def manage_tickets
#     @tickets = Ticket.all
#   end
#
#   def destroy_ticket
#     @ticket = Ticket.find(params[:id])
#     if @ticket.destroy
#       redirect_to manage_tickets_path, notice: 'Ticket deleted successfully.'
#     else
#       redirect_to manage_tickets_path, alert: 'Failed to delete ticket.'
#     end
#   end
#
#   private
#
#   def authenticate_admin!
#     redirect_to root_path, alert: 'Access Denied: Admins Only' unless current_user.admin?
#   end
#
#   # Set Movie for show creation
#   def set_movie
#     @movie = Movie.find(params[:movie_id]) if params[:movie_id]
#   end
#
#   # Set Show for ticket management
#   def set_show
#     @show = Show.find(params[:show_id]) if params[:show_id]
#   end
#
#   # Set user for editing profile
#   def set_user
#     @user = User.find(params[:id])
#   end
#
#   # Strong Parameters for user profile
#   def user_params
#     params.require(:user).permit(:name, :email, :address, :phone_number, :password, :password_confirmation)
#   end
#
#   # Strong Parameters for movie
#   def movie_params
#     params.require(:movie).permit(:title, :genre, :duration, :language, :rating, :release_date)
#   end
#
#   # Strong Parameters for show
#   def show_params
#     params.require(:show).permit(:date, :time, :seats_available, :ticket_price, :movie_id)
#   end
# end

class Admin::UsersController < Admin::ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'User successfully deleted.'
  end
end

app/controllers/user/base_controller.rb
module User
  class User::BaseController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # before_action :authenticate_user!
  # before_action :correct_user, only: %i[show edit update destroy]

  def show
    unless current_user == @user
      redirect_to home_index_path , notice: 'You are not permitted to view this page'
    end
  end

  def tickets
      @user = User.find(params[:id])
      if current_user.id != @user.id && current_user.username != 'Admin'
        flash[:alert] = "Access denied!"
        redirect_to home_index_path, notice: 'Access denied!'
      else
        @tickets = @user.tickets.includes(:show) # Fetch tickets with show details
     end
  end
  
  def new
    @user = User.new
  end

  def edit
    if current_user != @user && current_user.username != 'Admin'
      flash[:alert] = "Access denied!"
      redirect_to home_index_path, notice: 'Access denied!'
    end
  end

  def create
    @user = User.new(user_params)

    # if user is signing up, create new session and auto-login and redirect to user home page
    # else if admin is creating new user, continue with the admin session, redirect to admin dashboard
    if current_user&.username != "Admin"
      if @user.save
        session[:user_id] = @user.id
        redirect_to home_index_path, notice: "Account created successfully!"
      else
        flash[:alert] = @user.errors.full_messages.join(", ")
        render :new
      end
    else
      if @user.save
        redirect_to admin_dashboard_path, notice: "User created successfully!"
      else
        flash[:alert] = @user.errors.full_messages.join(", ")
        render :new
      end
    end

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: "User was successfully created." }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    if @user.update(user_params)
      if current_user.username == "Admin"
        redirect_to admin_dashboard_path, notice: "User profile was successfully updated."
      else
        redirect_to @user, notice: "Profile was successfully updated."
      end
    else
      render :edit
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    if current_user.username == "Admin"
      redirect_to admin_dashboard_path , status: :see_other, notice: "User was successfully destroyed."
    else
      redirect_to home_index_path , status: :see_other, notice: "User was successfully destroyed."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    redirect_to root_path, alert: "User not found" unless @user
  end

  def correct_user
    redirect_to root_path, alert: "Access denied!" unless @user == current_user
  end

  def user_params
    params.require(:user).permit(
      :name, :email, :phone_number, :address, :username, :password, :password_confirmation, :credit_card)
  end
end

app/helpers/user/base_helper.rb
module User::BaseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, url: user_signup_path, local: true) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation,style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :credit_card, style: "display: block" %>
    <%= form.text_field :credit_card %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= user.phone_number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Credit card:</strong>
    <%= user.credit_card %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing User" %>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editing User - Movie Ticketing System</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f9;
      margin: 0;
      padding: 0;
    }
    
    #notice {
      text-align: center;
      color: #e74c3c;
      font-size: 1.2em;
    }
    
    .container {
      max-width: 1500px;
      margin: 0 auto;
      padding: 20px;
    }
    
    .form-container {
      background-color: #fff;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
      width: 100%;
      max-width: 500px;
      text-align: center;
      margin: 0 auto;
    }
    
    .form-container h1 {
      color: #2c3e50;
      font-size: 2.5em;
      margin-bottom: 25px;
      font-weight: 600;
    }
    
    .form-group {
      margin-bottom: 25px;
    }
    
    label {
      display: block;
      font-size: 1.2em;
      color: #34495e;
      margin-top: 4px;
      margin-bottom: 4px;
      text-align: left;
    }
    
    input {
      width: 100%;
      padding: 7px;
      font-size: 1.1em;
      border: 1px solid #ccc;
      border-radius: 8px;
      box-sizing: border-box;
      transition: border-color 0.3s;
    }
    
    input:focus {
      border-color: #3498db;
      outline: none;
    }
    
    input[type="submit"] {
      background-color: #3498db;
      color: white;
      font-weight: bold;
      border: none;
      cursor: pointer;
      padding: 15px;
      font-size: 1.2em;
      border-radius: 8px;
      margin-top: 10px;
      width: 70%;
      transition: background-color 0.3s;
    }
    
    input[type="submit"]:hover {
      background-color: #2980b9;
    }
    
    .auth-links {
      margin-top: 15px;
      font-size: 1.1em;
    }
    
    .auth-links a {
      color: #3498db;
      text-decoration: none;
    }
    
    .auth-links a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>

  <div id="notice"><%= notice %></div>

  <div class="container">
    <div class="form-container">
      <h1>Editing User</h1>

<%= form_with(model: @user,local: true) do |form| %>
        <% if @user.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @user.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :username, style: "display: block" %>
          <% if @user.username == "Admin" %> <!-- admin is not allowed to change username -->
            <%= form.text_field :username, readonly: true %>
          <% else %>
            <%= form.text_field :username %> <!-- User is allowed to change username -->
          <% end %>
        </div>

        <div>
          <%= form.label :name, style: "display: block" %> <!-- admin and user allowed to change name -->
          <%= form.text_field :name %>
        </div>

          <div>
            <%= form.label :email, style: "display: block" %>
            <% if @user.username == "Admin" %> <!-- admin is not allowed to change password -->
              <%= form.text_field :email, readonly: true %>
            <% else %>
              <%= form.text_field :email %>
            <% end %>

          </div>

          <div>
            <%= form.label :password, style: "display: block" %>
            <% if @user.username == "Admin" %> <!-- admin is not allowed to change password -->
              <%= form.password_field :password, value: "SecurePass123", readonly: true %>
            <% else %>
              <%= form.password_field :password %>
            <% end %>
          </div>

          <div>
            <%= form.label :password_confirmation,style: "display: block" %>
            <% if @user.username == "Admin" %> <!-- admin is not allowed to change password -->
              <%= form.password_field :password_confirmation, value: "SecurePass123", readonly: true %>
            <% else %>
              <%= form.password_field :password_confirmation %>
            <% end %>
          </div>


        <div>
          <%= form.label :phone_number, style: "display: block" %>
          <%= form.text_field :phone_number %>
        </div>

        <div>
          <%= form.label :address, style: "display: block" %>
          <%= form.text_field :address %>
        </div>

        <div>
          <%= form.label :credit_card, style: "display: block" %>
          <%= form.text_field :credit_card %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      <% end %>
      <div class="auth-links">
        <%= link_to "Back to Profile", current_user&.username == "Admin" ? admin_dashboard_path : @user %> |
        <%= link_to "Back to Home",(current_user&.username == "Admin" ? admin_dashboard_path : home_index_path) %>
        <%# <%= link_to "Back to users", users_path %> 
      </div>
    </div>
  </div>

</body>
</html>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>
<br>
<%= link_to "Back to home page", root_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New User - Movie Ticketing System</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f9;
      margin: 0;
      padding: 0;
    }
    #notice {
      text-align: center;
      color: #e74c3c;
      font-size: 1.2em;
    }
    .container {
      max-width: 1500px;
      margin: 0 auto;
      padding: 20px;
    }
    .form-container {
      background-color: #fff;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
      width: 100%;
      max-width: 500px;
      text-align: center;
      margin: 0 auto;
    }
    .form-container h1 {
      color: #2c3e50;
      font-size: 2.5em;
      margin-bottom: 25px;
      font-weight: 600;
    }
    .form-group {
      margin-bottom: 25px;
    }
    label {
      display: block;
      font-size: 1.2em;
      color: #34495e;
      margin-top: 4px;
      margin-bottom: 4px;
      text-align: left;
    }
    input {
      width: 100%;
      padding: 7px;
      font-size: 1.1em;
      border: 1px solid #ccc;
      border-radius: 8px;
      box-sizing: border-box;
      transition: border-color 0.3s;
    }
    input:focus {
      border-color: #3498db;
      outline: none;
    }
    input[type="submit"] {
      background-color: #3498db;
      color: white;
      font-weight: bold;
      border: none;
      cursor: pointer;
      padding: 15px;
      font-size: 1.2em;
      border-radius: 8px;
      margin-top: 10px;
      width: 70%;
      transition: background-color 0.3s;
    }
    input[type="submit"]:hover {
      background-color: #2980b9;
    }
    .auth-links {
      margin-top: 15px;
      font-size: 1.1em;
    }
    .auth-links a {
      color: #3498db;
      text-decoration: none;
    }
    .auth-links a:hover {
      text-decoration: underline;
    }
  </style>
</head>
<body>

  <div id="notice"><%= notice %></div>
  <div class="container">
    <div class="form-container">
      <h1>New User</h1>

      <%= render "form", user: @user %>

      <% if current_user&.username != "Admin" %>
        <div class="auth-links">
          <%= link_to "Login Instead", home_index_path %>
        </div>
      <% end %>
    </div>
  </div>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Details</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f9;
      margin: 0;
      padding: 0;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    .notice {
      color: green;
      text-align: center;
      font-size: 1.2em;
      margin-bottom: 20px;
    }
    .user-info {
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      margin-bottom: 20px;
    }
    .user-info h2 {
      font-size: 2em;
      margin-bottom: 10px;
    }
    .user-info p {
      font-size: 1.1em;
      margin-bottom: 20px;
    }
    .user-links {
      display: flex;
      justify-content: space-between;
      margin-top: 20px;
    }
    .user-links a,
    .user-links button {
      padding: 12px 20px;
      background-color: #3498db;
      color: white;
      text-decoration: none;
      border-radius: 5px;
      font-size: 1.1em;
    }
    .user-links a:hover,
    .user-links button:hover {
      background-color: #2980b9;
    }
    .user-links .button-delete {
      background-color: #e74c3c;
    }
    .user-links .button-delete:hover {
      background-color: #c0392b;
    }
  </style>
</head>
<body>

  <div class="container">
    <p class="notice"><%= notice %></p>

    <div class="user-info">
      <%= render @user %>
    </div>

    <div class="user-links">
      <% if current_user&.username != "Admin" %>
        <%= link_to "View My Tickets", tickets_user_path(@user) %>
      <% end %>
      <%= link_to "Edit Details", edit_user_path(@user) %>
      <% if current_user&.username == "Admin" %>
        <%= link_to "Back to Admin Dashboard", admin_dashboard_path %>
      <% else %>
        <%= link_to "Back to Home Page", home_index_path %>
      <% end %>
      <% if current_user&.username != "Admin" %>
        <%= button_to "Destroy User", @user, method: :delete, class: "button-delete" %>
      <% end %>
    </div>
  </div>

</body>
</html>

app/views/users/tickets.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Tickets</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f9;
      margin: 0;
      padding: 0;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      text-align: center;
      color: #2c3e50;
      margin-bottom: 40px;
    }
    .ticket-list {
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    .ticket-list ul {
      list-style-type: none;
      padding: 0;
    }
    .ticket-list li {
      padding: 10px;
      border-bottom: 1px solid #ddd;
      font-size: 1.2em;
    }
    .ticket-list li:last-child {
      border-bottom: none;
    }
    .ticket-list strong {
      color: #3498db;
    }
    .no-tickets {
      text-align: center;
      font-size: 1.2em;
      color: #e74c3c;
    }
    .back-links {
      display: flex;
      justify-content: center;
      gap: 20px;
      margin-top: 40px;
    }
    .back-links a {
      font-size: 1.2em;
      color: #3498db;
      text-decoration: none;
    }
    .back-links a:hover {
      text-decoration: underline;
    }
    .delete-btn {
  background-color: #e74c3c;
  color: white;
  font-size: 0.8em;
  padding: 5px 12px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.delete-btn:hover {
  background-color: #c0392b;
}
.flash-message {
  text-align: center;
  font-size: 1.2em;
  padding: 10px;
  border-radius: 5px;
  margin-bottom: 20px;
}

.success {
  background-color: #2ecc71;
  color: white;
}

.error {
  background-color: #e74c3c;
  color: white;
}



  </style>
</head>
<body>

  <div class="container">
 
    <h1>My Tickets</h1>

    <div class="ticket-list">
      <% if @tickets.any? %>
        <ul>
          <% @tickets.each do |ticket| %>
            <li>
              🎟 Ticket for <strong><%= ticket.show.movie.title %></strong> 
              on <%= ticket.show.date %> at <%= ticket.show.time %><br>
              Status: <%= ticket.status %>
              <% if ticket.status != "Cancelled" %>
              <%= button_to "Cancel Ticket", cancel_ticket_path(ticket), method: :get,
                    data: { confirm: "Are you sure you want to cancel this ticket?" },
                    class: "delete-btn" %>
              <% end %>
                    
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="no-tickets">No tickets booked yet.</p>
      <% end %>
    </div>
     <% if flash[:notice] %>
      <p class="flash-message success"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <p class="flash-message error"><%= flash[:alert] %></p>
    <% end %>
    <div class="back-links">
      
      <%= link_to "Go to Profile", user_path(@user) %>
      <%= link_to "Back to Home", home_index_path %>
    </div>
  </div>

</body>
</html>